deadline-check-hw1:
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'hw1'
  stage: deadline_check
  script: if [ "$(date '+%Y-%m-%d %H:%M:%S')" \< "$HW1_HARD_DEADLINE" ]; then exit 0; else echo "Deadline reached"; exit 1; fi

check-changes-hw1:
  stage: base_check
  needs:
    - deadline-check-hw1
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'hw1'
  image: registry.gitlab.v-efimov.tech/vk_education/images/bmstu_ml_spring_2025/hw1:latest
  script:
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - CHANGED_FILES=$(git diff --name-only HEAD origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME)
    - if [ "$CHANGED_FILES" = "hw1/solution.py" ]; then exit 0; else exit 1; fi

test-solution-hw1:
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'hw1'
  image: registry.gitlab.v-efimov.tech/vk_education/images/bmstu_ml_spring_2025/hw1:latest
  stage: test
  needs:
    - check-changes-hw1
    - flake8
    - check-correct-branch
  script: python -m pytest --log-cli-level INFO hw1/

success-hw1:
  stage: success
  needs:
    - test-solution-hw1
  rules:
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == 'hw1'
  image: registry.gitlab.v-efimov.tech/vk_education/images/bmstu_ml_spring_2025/hw1:latest
  script:
    - MESSAGE_FULL='%E2%9C%85%20%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%BE%20%D0%BD%D0%B0%20%D0%BF%D0%BE%D0%BB%D0%BD%D1%8B%D0%B9%20%D0%B1%D0%B0%D0%BB%D0%BB%2C%20%D0%B8%D1%82%D0%BE%D0%B3%D0%BE%D0%B2%D0%B0%D1%8F%20%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B0%3A%2010%20%D0%B1%D0%B0%D0%BB%D0%BB%D0%BE%D0%B2.'
    - MESSAGE_HALF='%E2%9A%A0%EF%B8%8F%20%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%B2%D1%8B%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%BE%20%D1%81%20%D0%BE%D0%BF%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5%D0%BC%2C%20%D0%B8%D1%82%D0%BE%D0%B3%D0%BE%D0%B2%D0%B0%D1%8F%20%D0%BE%D1%86%D0%B5%D0%BD%D0%BA%D0%B0%3A%205%20%D0%B1%D0%B0%D0%BB%D0%BB%D0%BE%D0%B2.'
    - >
      if [ "$(date '+%Y-%m-%d %H:%M:%S')" \< "$HW1_SOFT_DEADLINE" ];
      then
        curl --silent --request POST --header "PRIVATE-TOKEN: $GRADER_API_KEY" --url "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes?body=$MESSAGE_FULL";
      else
        curl --silent --request POST --header "PRIVATE-TOKEN: $GRADER_API_KEY" --url "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes?body=$MESSAGE_HALF";
      fi